
import mss
from PIL import Image, ImageGrab
import pyautogui

import time

# Screenshots with PIL is very simple
def screenshot_pil(output_path="screenshot.png"):
    img = ImageGrab.grab()
    img.save(output_path)
    return img

# Screenshots with pyautogui is also very simple
# However this is just a wrapper over PIL 
def screenshot_pyautogui(output_path="screenshot.png"):
    img = pyautogui.screenshot()
    img.save(output_path)
    return img

# Screenshots with MSS

def screenshot_mss(output_path="screenshot.png"):
    with mss.mss() as sct:
        sct_img = sct.grab(sct.monitors[1]) #allows you to choose the monitor
    img = Image.frombytes("RGB", sct_img.size, sct_img.bgra, "raw", "BGRX")
    img.save(output_path)
    return img


def screenshot_mss_region(x, y, w, h, output_path="screenshot_region.png"):
    with mss.mss() as sct:
        monitor = {"top": y, "left": x, "width": w, "height": h}
        sct_img = sct.grab(monitor)
    img = Image.frombytes("RGB", sct_img.size, sct_img.bgra, "raw", "BGRX")
    img.save(output_path)
    return img

# Quartz may also be worthwhile to look at 

# this function was generated by claude to benchmark different screenshots
def benchmark(runs=5):
    methods = {
        "mss":        screenshot_mss,
        "PIL":        screenshot_pil,
        "pyautogui":  screenshot_pyautogui,
    }
    results = {}
    
    for name, fn in methods.items():
        times = []
        for _ in range(runs):
            t0 = time.perf_counter()
            try:
                fn()
            except Exception as e:
                print(f"{name} failed: {e}")
                break
            times.append(time.perf_counter() - t0)
        if times:
            avg = sum(times) / len(times)
            results[name] = round(avg * 1000, 2)
            print(f"{name:12} avg: {avg*1000:.1f}ms")
    return results
    

if __name__ == "__main__":
    print(f"benchmarking...\n")
    benchmark()